export const FETCH_ALL = 'FETCH_ALL';
export const ADD_DONATION = 'ADD_DONATION';
export const UPDATE_DONATION='UPDATE_DONATION';
export const DELETE_DONATION = "DELETE_DONATION";
export const SORT_DONATIONS="SORT_DONATIONS";
export const SET_EDIT_DATA="SET_EDIT_DATA";
export const SET_GEN_DATA='SET_GEN_DATA';
export const LOGIN='LOGIN';
